config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :admirers, :messages_to, :messages_from
    end
  end

  resources :sessions, :only=> [:new, :create, :destroy]
  resources :microposts, :only=> [:destroy]
  resources :relationships, :only=> [:create, :destroy]

  match '/signup',  :to=> 'users#new'
  match '/profile',  :to=> 'users#show'
  match '/signin',  :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete

  match '/contact', :to=> 'static_pages#contact'
  match '/about', :to=> 'static_pages#about'
  match '/help',  :to=> 'static_pages#help'
  
  match '/courses', :to=> 'users#index' 
   match '/course',  :to=> 'static_pages#courses'
    match '/bugs',  :to=> 'static_pages#bug'
    match '/teach',  :to=> 'static_pages#teach'
    match '/html5',  :to=> 'static_pages#les1'
     match '/android',  :to=> 'static_pages#les2'
 match '/home',  :to=> 'static_pages#home'
  root      :to=> 'users#index'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(:page=> params[:page])
    end
  end

  def contact
  end

  def about
  end

  def help
  end

end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

	


</br>
</br>
</br>
</br>
</br>
</br>

 <img src="http://i45.tinypic.com/2556z9d.png"/></a> 
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

</br>
</br>
</br>

</br>



 <img src="http://i45.tinypic.com/2lj2g3l.png"/>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
 <img src="http://i47.tinypic.com/16gy70i.png"/>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
 <img src="http://i49.tinypic.com/w9u3wl.png"/>
 </br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
 <img src="http://i47.tinypic.com/2vlpeoj.png"/>
 </br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
 <img src="http://i46.tinypic.com/2mcysnk.png"/>
 </br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
 <img src="http://i49.tinypic.com/14p9iu.png"/>
 </br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

    
   
    <br>
<br>
</div>
</div>
      <%= render 'layouts/footer' %>
</div>

app/views/static_pages/bug.html.erb
<% provide(:title, 'About Us') %>

	


</br>
</br>
</br>
</br>
</br>
</br>

 <img src="http://i47.tinypic.com/153p440.png"/></a> 
</br>



</br>
</br>
</br>

</br>



 <% if signed_in? %> | <%= link_to "View Profie", user_path(current_user) %>| <%= link_to "Settings", edit_user_path(current_user) %>  | <%=link_to "Log Out", signout_path, :method=> :delete %> <% end %> </center>
<br>
<br>
    
   
    <br>
<br>

   <center> Copyright 2013 OrangeApps © All Rights Reserved. </center>
</br>
</br>
</br>

</br>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

	<covers><%= link_to image_tag("http://i46.tinypic.com/289g6zo.jpg")%></covers>
	<kiido><center>Contact</center></kiido>

app/views/static_pages/courses.html.erb
<% provide(:title, 'Course') %>

<center> <img src="http://i49.tinypic.com/2q9mazt.png" alt="" />
 

<center><div class="container">  
<ul class="thumbnails">  
        <li class="span6">  
          <div class="thumbnail">  
            <img src="http://i47.tinypic.com/qsqbsi.png" alt="product 1">  
            <div class="caption">  
              
              <h5>Product detail</h5>  
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore       magna aliqua.</p>  
              <p><a href="#" class="btn btn-success">Enroll</a> </p>  
            </div>  
          </div>  
        </li>  
        <li class="span6">  
          <div class="thumbnail">  
            <img src="http://i47.tinypic.com/qsqbsi.png" alt="product 2">  
            <div class="caption">  
              <h5>Product detail</h5>  
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>  
            <p><a href="/users/2" class="btn btn-success">Enroll</a> </p>  
            </div>  
          </div> 
             <li class="span3">  
          <div class="thumbnail">  
            <img src="http://i47.tinypic.com/qsqbsi.png" alt="product 2">  
            <div class="caption">  
              <h5>Product detail</h5>  
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>  
            <p><a href="#" class="btn btn-success">Enroll</a> </p>  
            </div>  
             <li class="span3">  
          <div class="thumbnail">  
            <img src="http://i47.tinypic.com/qsqbsi.png" alt="product 2">  
            <div class="caption">  
              <h5>Product detail</h5>  
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>  
             <p><a href="#" class="btn btn-success">Enroll</a> </p>  
            </div>    
             <li class="span3">  
          <div class="thumbnail">  
            <img src="http://i47.tinypic.com/qsqbsi.png" alt="product 2">  
            <div class="caption">  
              <h5>Product detail</h5>  
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>  
         <p><a href="#" class="btn btn-success">Enroll</a> </p>   
            </div>  
             <li class="span3">  
          <div class="thumbnail">  
            <img src="http://i47.tinypic.com/qsqbsi.png" alt="product 2">  
            <div class="caption">  
              <h5>Product detail</h5>  
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>  
          <p><a href="#" class="btn btn-success">Enroll</a> </p>  
            </div>    
             <li class="span3">  
          <div class="thumbnail">  
            <img src="http://i47.tinypic.com/qsqbsi.png" alt="product 2">  
            <div class="caption">  
              <h5>Product detail</h5>  
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>  
               <p><a href="#" class="btn btn-success">Enroll</a> </p>  
            </div>   
             <li class="span3">  
          <div class="thumbnail">  
            <img src="http://i47.tinypic.com/qsqbsi.png" alt="product 2">  
            <div class="caption">  
              <h5>Product detail</h5>  
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>  
             <p><a href="#" class="btn btn-success">Enroll</a> </p>  
            </div>   
             <li class="span3">  
          <div class="thumbnail">  
            <img src="http://i47.tinypic.com/qsqbsi.png" alt="product 2">  
            <div class="caption">  
              <h5>Product detail</h5>  
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>  
              <p><a href="#" class="btn btn-success">Enroll</a> </p>  
            </div>   
              <li class="span3">  
          <div class="thumbnail">  
            <img src="http://i47.tinypic.com/qsqbsi.png" alt="product 2">  
            <div class="caption">  
              <h5>Product detail</h5>  
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>  
              <p><a href="#" class="btn btn-success">Enroll</a> </p>  
            </div>   

        </li>  
      </ul>  
  
      <hr>  
  


   
    </div>


</div>
</div>
      <%= render 'layouts/footer' %>
    </body>



    

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Technopreneurship</h1>
<p>
   <img src="http://i47.tinypic.com/nzgcna.png" alt="" />
     
Get help on Ruby on Rails Tutorial at the
<a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
To get help on this sample app, see the
<a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>
<p>
Added/modified functionality:
<ul>
  <li>User has the 'username' attribute, which is non-editable after signing up</li>
  <li>User index page has a search form to search for all users by username</li>
  <li>Admin users can delete other admin users</li>
  <li>Signin is by username and password</li>
  <li>Users have direct messages</li>
  <ul>
    <li>They can only be viewed by the sender and receiver</li>
    <li>They can only be sent to followers</li>
    <li>Pages to view them are accessible under the new Messages nav bar drop down</li>
  </ul>
  <li>Users can use the micropost form to perform other actions:
  <ul>
    <li>Reply to other users by prefixing posts with <i>@[username]</i></li>
    <li>Follow other users by typing <i>follow [username]</i> or <i>f [username]</i></li>
    <li>Unfollow a user by typing <i>unfollow [username]</i></li>
    <li>
    Send a direct message to a follower by typing
    <i>dm [username] [message text]</i> or 
    <i>m [username] [message text]</i>
    </li>
  </ul>
</ul>
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>

  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <!--%= render 'shared/micropost_form' %-->
        <%= render 'shared/parser_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3><k>What's happening?</k></h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>

  <%= render "shared/home" %>
<% end %>

app/views/static_pages/les1.html.erb
<% provide(:title, 'HTML5') %>
<body class="responsive">
<br>
<br>
<br>
<br>
<br>
<h1>TOPIC: HTML 5 </h1>
<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  <img src="http://i47.tinypic.com/2w382nr.png"/></a> 
<br>

<H2> ABOUT THE COURSE</H2>
<p>

Students will study the main concepts of HTML 5, HTML5 is a markup language for structuring and presenting content for the World Wide Web and a core technology of the Internet. It is the fifth revision of the HTML standard (created in 1990 and standardized as HTML 4 as of 1997) and, as of December 2012, is a W3C Candidate Recommendation. Its core aims have been to improve the language with support for the latest multimedia while keeping it easily readable by humans and consistently understood by computers and devices (web browsers, parsers, etc.). HTML5 is intended to subsume not only HTML 4, but XHTML 1 and DOM Level 2 HTML as well.
<br>
<br>

<%= form_for(:signin, :url=> root_path) do |f| %>
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;<%= f.submit "Enrollment is not yet open", :class=> "btn btn-large btn-primary" %>
    <% end %>
</p>
</body>

app/views/static_pages/les2.html.erb
<% provide(:title, 'HTML5') %>
<br>
<br>
<br>
<br>
<br>
<h1>TOPIC: Android Development 1.0 </h1>
<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  <img src="http://i47.tinypic.com/aczdi1.png"/></a> 
<br>

<H2> ABOUT THE COURSE</H2>
<p>

Students will study how to code the basics of Android Development, Android is a Linux-based operating system designed primarily for touchscreen mobile devices such as smartphones and tablet computers. Initially developed by Android, Inc., which Google backed financially and later bought in 2005, Android was unveiled in 2007 along with the founding of the Open Handset Alliance: a consortium of hardware, software, and telecommunication companies devoted to advancing open standards for mobile devices. The first Android-powered phone was sold in October 2008.
<br>
<br>

<%= form_for(:signin, :url=> root_path) do |f| %>
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;<%= f.submit "Enrollment is not yet open", :class=> "btn btn-large btn-primary" %>
    <% end %>
</p>

app/views/static_pages/teach.html.erb
 	<% provide(:title, 'Teachers') %>

	

</br>
</br>
</br>
<h1>We want you to help and Earn at the same time</h1>
</br>
</br>
<h2>Set your class and Teach!</h2>



 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;   <br> <center>  <img src="http://i50.tinypic.com/vsjmvc.png"/></a> 
<br>

</br>
</br>
</br>
</br>
</br>

<h1>How ?</h1>



 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;   <br> <center>  <img src="http://i49.tinypic.com/1fdy6a.png"/></a> 
<br>
<br>

</br>
</br>
<br>
<br>

</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
<h1>Easy right ? Sign up now </h1>
</br>



<%= form_for(:signin, :url=> signin_path) do |f| %>
  <%= f.submit "I WANT TO TEACH", :class=> "btn btn-large btn-primary" %>
    <% end %>

    </br>
</br>
<br>
<br>

</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
<center><h3><%= link_to "Courses", course_path %> | <%= link_to "About", about_path %> | <%= link_to "Team", root_path %> | <%= link_to "Universities", root_path %> | <%= link_to "Teachers", root_path %> </center>

<br>
<br>
    
   
    <br>
<br>

   <center> Copyright 2013 OrangeApps © All Rights Reserved. </center>

</div>