config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :admirers, :messages_to, :messages_from
    end
  end

  resources :sessions, :only=> [:new, :create, :destroy]
  resources :microposts, :only=> [:destroy]
  resources :relationships, :only=> [:create, :destroy]

  match '/signup',  :to=> 'users#new'
  match '/profile',  :to=> 'users#show'
  match '/signin',  :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete

  match '/contact', :to=> 'static_pages#contact'
  match '/about', :to=> 'static_pages#about'
  match '/help',  :to=> 'static_pages#help'
  
  match '/courses', :to=> 'users#index' 
   match '/course',  :to=> 'static_pages#courses'
    match '/bugs',  :to=> 'static_pages#bug'
    match '/teach',  :to=> 'static_pages#teach'
    match '/html5',  :to=> 'static_pages#les1'
     match '/android',  :to=> 'static_pages#les2'
 match '/home',  :to=> 'static_pages#home'
  root      :to=> 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # note :admin is excluded, so malicatious user cannot send a PUT
  # requset to make arbitraty users admins.
  attr_accessible :name, :username, :email, :password, :password_confirmation, :school, :location, :status
  has_secure_password

  has_many :microposts, :dependent=> :destroy
  has_many :relationships, :foreign_key=> "follower_id",
    :dependent=> :destroy
  has_many :followed_users, :through=> :relationships, :source=> :followed

  has_many :reverse_relationships, :foreign_key=> "followed_id",
    :class_name=> "Relationship",
    :dependent=> :destroy
  has_many :followers, :through=> :reverse_relationships, :source=> :follower

  has_many :sent_messages, :class_name=> "Message", :foreign_key=> :from_user_id,
    :dependent=> :destroy
  has_many :received_messages, :class_name=> "Message", :foreign_key=> :to_user_id,
    :dependent=> :destroy

  VALID_EMAIL_REGEX =/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_USERNAME_REGEX = /\A\w+\z/

  validates :name,  :presence=> true,
    :length=> { :maximum=> 50 }

  validates :username, :presence=> true,
    :format=>  { :with=> VALID_USERNAME_REGEX },
    :length=> { :maximum=> 15 },
    :uniqueness=> { :case_sensitive=> true }

  validates :email, :presence=>   true,
    :format=>     { :with=> VALID_EMAIL_REGEX },
    :uniqueness=> { :case_sensitive=> false }

  # automatically created the virtual attribute password_confirmation
  validates :password, :presence=> true,
    :length=> { :minimum=> 6 }
  validates :password_confirmation, :presence=> true

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  default_scope :order=> :username

  # method to search all Users by username.
  # uses method 'paginate', which applies finder options
  # (github.com/mislav/will_paginate/blob/master/lib/will_paginate/active_record.rb)
  def self.search(username, page)
    paginate :page=> page, :conditions=> ['username like ?', "%#{username}%"]
  end

  def feed
    Micropost.from_users_followed_by(self)
  end

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(:followed_id=> other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user).destroy
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.base64.tr("+/", "-_")
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Filters are applied in order of appearance!
  before_filter :signed_in_user, :only=> [:index, :edit, :update, :destroy, :following, :followers, :messages_to, :messages_from]
  before_filter :correct_user, :only=> [:edit, :update, :messages_to, :messages_from]
  before_filter :admin_user, :only=> :destroy
  before_filter :admin_cannot_delete_self, :only=> :destroy
  before_filter :not_for_authenticated_users, :only=> [:new, :create]

  def index
    @users = User.search(params[:search], params[:page])
    if @users.empty?
      flash.now[:error] = "No users found."
    end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page=> params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Kiido.ph!"

      redirect_to users_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(:page=> params[:page])
    render 'show_follow'
  end

  def admirers
    @title = "Enrolled"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(:page=> params[:page])
    render 'show_follow'
  end

  def messages_to
    @title = "Received Messages"
    @user = User.find(params[:id])
    @messages = @user.received_messages.paginate(:page=> params[:page])
    render 'show_messages'
  end

  def messages_from
    @title = "Sent Messages"
    @user = User.find(params[:id])
    @messages = @user.sent_messages.paginate(:page=> params[:page])
    render 'show_messages'
  end

  private

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  def not_for_authenticated_users
    if signed_in?
      redirect_to root_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_cannot_delete_self
    @user = User.find(params[:id])
    if @user.admin? and current_user?(@user)
      redirect_to users_path, :notice=> "Admin user cannot delete self!"
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size=> 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, :alt=> user.username, :class=> "gravatar")
  end
end

app/views/users/_edit_fields.html.erb
<%= render 'shared/error_messages', :object=>  f.object %>

<%= hidden_field(:user, :username) %>

<h3>Professor Name</h3>
<%= f.text_field :name%>

<h3>Course Title</h3>
<%= f.text_field :status%>

<h3>Course Description</h3>
<%= f.text_area :location %>

<h3>Time</h3>
<%= f.text_field :school %>

<h3>Password</h3>
<%= f.password_field :password %>

<h3>Confirm Password</h3>
<%= f.password_field :password_confirmation %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object=>  f.object %>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation %>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(:followed_id=> @user.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <k><%= f.submit "Enroll", :class=> "btn btn-large btn-primary" %></k>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_search.html.erb
<div class="row">
  <div class ="span6 offset3">
    <%= form_tag users_path, :method=> 'get' do %>
      <%= text_field_tag :search, params[:search], :placeholder=> "Search by username"%>
      <%= submit_tag "Search", :class=> "btn btn-small btn-primary", :name=> nil %>
    <% end %>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             :html=> { :method=> :delete }) do |f| %>
  <k><%= f.submit "Drop", :class=> "btn btn-large" %></k>
<% end %>

app/views/users/_user.html.erb
<li>
<%=  image_tag avatarzz_url user %><br>
<br>
<%= user.username  %>

  
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Create your Class</h1>

<div class="row">

  <div class="span8 offset2">
  	<center>
  	<%= image_tag avatarzz_url current_user, :size=> 50  %>
  </br>
    <a href="http://gravatar.com/emails">Change Photo</a>
    </center>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', :object=> f.object %>
      <%= render 'edit_fields', :f => f %>
      <%= f.submit "Update", :class=> "btn btn-large btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Courses') %>
<% if signed_in? %>




</br>
</br>
</br>
</br>
</br>
</br>

 <img src="http://i47.tinypic.com/153p440.png"/></a> 
</br>



</br>
</br>
</br>

</br>



<center><h3> <% if signed_in? %> <%= link_to "View Profie", user_path(current_user) %>| <%= link_to "Settings", edit_user_path(current_user) %>  | <%=link_to "Log Out", signout_path, :method=> :delete %> <% end %> </center>
<br>
<br>
    
   
    <br>
<br>

   <center> Copyright 2013 OrangeApps © All Rights Reserved. </center>
</br>
</br>
</br>

</br>
</div>
<% else %>
  <%= render "shared/home" %>
<% end %>
</br>
</br>
</br>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<body>
	

</br>
</br>


</br>

<h1>Welcome to kiido.ph Join our free classes</h1>

</br>

<div id="signingup">
<div class="row">
	
  <div class="span6 offset7">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', :object=> f.object %>
      <%= render 'fields', :f => f %>
      <center><%= f.submit "Sign up", :class=> "btn btn-large btn-primary" %></center>
    <% end %>
</div>
  </div>
</div>
</div>
    </br>
</br>
</br>
</br>
</br>

<center> Copyright 2013 OrangeApps © All Rights Reserved. </center>
</br>
</br>
</br>
</br>
</br>
</br>

</body>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<body class="responsive">
<div class="span11">
<h3>
    <center><%= image_tag avatar_url @user, :size=> 50  %></center>
    <center><%= @user.status %></center>
</h3>

<h3>
<center class="status">
  <a href="<%= admirers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Enrolled Students
  </a>
</center>
</h3>
<center>
<section class="btnfllow"><%= render "follow_form" if signed_in? %></section>
</center>
</br>
<section class="left">
<algnleft><b>Professor:</b> <%= @user.name %></algnleft></br>
<algnleft><b>Time:</b> <%= @user.school %></algnleft></br>  
<algnleft><b>Course Description:</b> <%= @user.location %></p></algnleft>
</section>

</br>
</div>
<div class="span8 bottom">
  <% if @user.microposts.any? %>
    <h3><k>Wall Feed (<%= @user.microposts.count %>)</k></h3>
    <ol class="microposts span6">
      <%= render @microposts %>
    </ol>
  <% end %>
</div>
</div>
</body>

app/views/users/show_blank.html.erb
<% provide(:title, @user.username) %>
<div class="row">
  <aside class="span4">
  <section>
    
  <h1>
    <center><%= image_tag avatar_url current_user, :size=> 50  %></center>
  </br>
    <center><%= @user.name %></center>
  </h1>
  </section>
  <section>
  <%= render 'shared/stats' %>
  </section>
  </aside>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<body class="responsive">
<div class="row">
  <div class="span7 offset5 padding">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>
</body>

app/views/users/show_messages.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <center><%= image_tag avatarzz_url current_user %></center>
    </section>
     <center> <%= @user.username %> </center>
  <section>
    <%= render 'shared/stats' %>
  </section>
  </aside>
  <div class="span8">
      <h3><k><%= @title %> (<%= @messages.count %>)</k></h3>
    <% if @messages.any? %>
      <ol class="microposts">
        <%= render :partial=> "users/message", :collection=> @messages %>
      </ol>
      <%= will_paginate @messages %>
    <% else %>
      <k>No messages!</k>
    <% end %>
  </div>
</div>