config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :admirers, :messages_to, :messages_from
    end
  end

  resources :sessions, :only=> [:new, :create, :destroy]
  resources :microposts, :only=> [:destroy]
  resources :relationships, :only=> [:create, :destroy]

  match '/signup',  :to=> 'users#new'
  match '/profile',  :to=> 'users#show'
  match '/signin',  :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete

  match '/contact', :to=> 'static_pages#contact'
  match '/about', :to=> 'static_pages#about'
  match '/help',  :to=> 'static_pages#help'
  
  match '/courses', :to=> 'users#index' 
   match '/course',  :to=> 'static_pages#courses'
    match '/bugs',  :to=> 'static_pages#bug'
    match '/teach',  :to=> 'static_pages#teach'
    match '/html5',  :to=> 'static_pages#les1'
     match '/android',  :to=> 'static_pages#les2'
 match '/home',  :to=> 'static_pages#home'
  root      :to=> 'users#index'

end

app/views/layouts/_car.html.erb
<% if signed_in? %>
<% else %>
<car class="car">
  <Br>
    <Br>
      <Br>
        <Br>
    <Br>
      <Br>
        <Br>
    <Br>
      <Br>
 



  <center><h3><%= link_to "Courses", course_path %> | <%= link_to "About", about_path %> | <%= link_to "Team", root_path %> | <%= link_to "Universities", root_path %> | <%= link_to "Teachers", root_path %> </center>
<center> Copyright 2013 OrangeApps © All Rights Reserved. </center>
</car>
<% end %>

app/views/layouts/_footer.html.erb
<% if signed_in? %>
<% else %>
<br>
<br><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



  <center><h3><%= link_to "Courses", root_path, :class => "newsomething" %> | <%= link_to "About",  root_path, :class => "newsomething" %> | <%= link_to "Team", root_path, :class => "newsomething" %> | <%= link_to "Universities", root_path, :class => "newsomething" %> | <%= link_to "Teachers", root_path, :class => "newsomething" %> </center>
</br>
<center>iPhone is a trademark of Apple Inc. App Store is a service mark of Apple Inc.
Kiido is made for the everyone who wants to learn anytime and anywhere they want
<center> Copyright 2013 OrangeApps © All Rights Reserved. </center>
<%= link_to image_tag("http://i50.tinypic.com/2l9l7wm.png")%>
</footer>
<% end %>

app/views/layouts/_header.html.erb
<% if signed_in? %>

<header class="navbar navbar-fixed-top">
<div class="navigatebar-inner ">
  <div class="container">

    <nav>
      <%= link_to image_tag("iconss.png", :id=> "logo"), root_path  %>
    <ul class="nav pull-right menu">

    

      <li><%= link_to "Home", root_path, :id=> "text" %></li>
     
      <li><%= link_to "Courses", course_path, :id=> "text" %></li>
      <li><%= link_to "About ", about_path, :id=> "text" %></li>
     
      
      
        <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" id= "text"  >
            Account
          </a>
          <ul class="dropdown-menu menu">
           
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
            <%= link_to "Sign out", signout_path, :method=> :delete %>
            </li>
          </ul>
        </li>
    </ul>
    </nav>
  </div>
</div>
</header>


  <% end %>

app/views/layouts/_test.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/stylesheets/bootstrap-responsive.css" rel="stylesheet">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", :media=> "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <!--[if lt IE 9]>
    <script src="http://html5shim/googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script type="text/javascript">



</script>
  </head>
 <body background="jj.png">
    
    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    


    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/stylesheets/bootstrap-responsive.css" rel="stylesheet">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", :media=> "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <!--[if lt IE 9]>
    <script src="http://html5shim/googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-39121685-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  </head>
  <body>
    
    <div class="container">
      <!--%= render 'layouts/header' %>
      <!-->
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
     
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/cartest.html.erb
<% provide(:title, 'Home ') %>
</div>
 </div>




</br>
</br>
</br>
</br>
</br>

</br>
</br>
</br>
</br>
</br>

<h7>Join our first Class</h7>
<br>
<br>
<br>
<br>
<h7>Topic: HTML 5 </h7>
<br>
<br>
&nbsp;<h8>HTML 5 for Everyone</h8>

<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  <img src="http://i47.tinypic.com/2w382nr.png"/></a> 
<br>
<br>

<%= form_for(:signin, :url=> html5_path) do |f| %>
 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;<%= f.submit "Enroll Now", :class=> "btn btn-large btn-primary" %>
    <% end %>

</ul>
<br>
<br>
<br>
<br>

<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1>Easy as 1 2 3</h1>
<br>
<br> <center>  <img src="http://i45.tinypic.com/3582rts.png"/></a> 
<br>
<br>
<br>
<br>
<br>
<br>


 <h1>We want you  to make a change Be a Teacher !</h1>

 <br> <center>  <img src="http://i50.tinypic.com/vsjmvc.png"/></a> 
<br>
<br>

<%= form_for(:teach, :url=> teach_path) do |f| %>
 <%= f.submit "Apply Now", :class=> "btn btn-large btn-primary" %>
    <% end %>

<br>

<br>
<br>
<br>

<br>
<br>
<br>


 <center><h3><%= link_to "Courses", course_path %> | <%= link_to "About", about_path %> | <%= link_to "Team", root_path %> | <%= link_to "Universities", root_path %> | <%= link_to "Teachers", root_path %> </center>

<br>
<br>
    
   
    <br>
<br>

   <center> Copyright 2013 OrangeApps © All Rights Reserved. </center>
    </div>
    </body>